
services:
    repository.space:
        class: Duti\Bundle\Core\Repository\SpaceRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: [Duti\Bundle\Core\Entity\DataSource]

