
services:
    repository.space:
        class: Duti\Bundle\Core\Repository\SpaceRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: [Duti\Bundle\Core\Entity\Space]

    repository.project:
        class: Duti\Bundle\Core\Repository\ProjectRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: [Duti\Bundle\Core\Entity\Project]

    repository.task:
        class: Duti\Bundle\Core\Repository\TaskRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: [Duti\Bundle\Core\Entity\Task]
